# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and Deploy Python app to Azure Linux Web App using uv

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.x'           # Set this to the Python version to use
  AZURE_WEBAPP_NAME: 'my-app'      # Set this to your application's name
  WORKING_DIRECTORY: '.'           # Set this to the path to deploy to Web App. Defaults to the repository root
  STARTUP_COMMAND: ''              # Set this to the startup command required to start the application. Default is gunicorn for Flask/Django apps. Best practice: When using startup commands besides gunicorn with a pyproject.toml and uv.lock deployment setup, explicitly mention python3 with the startup command such as 'python3 -m uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Create virtual environment and Generate lock file and install dependencies into antenv
        run: |
          uv venv antenv
          source antenv/bin/activate
          uv lock
          uv sync --no-dev

      # Optional: Run tests before deploying
      # Uncomment the following step to run tests with pytest or your preferred test framework
      # - name: Run tests
      #   run: |
      #     uv run pytest tests/
      # If you need dev dependencies for testing, use: uv sync --all-groups or uv sync (without --no-dev)

      # If the SCM_DO_BUILD_DURING_DEPLOYMENT setting is enabled (set to true), the platform uses Oryx during deployment to build the application and install dependencies (for example, running `pip install`). Since the build happens on the platform, we exclude the antenv virtual environment folder from the deployment package. This helps reduce the size of the deployment artifact and avoids sending unnecessary files that will be recreated during the build process.
      - name: Cleanup Venv for Deployment
        run: |
          rm -rf antenv


      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.WORKING_DIRECTORY }}
          startup-command: ${{ env.STARTUP_COMMAND }}

      - name: Logout from Azure
        if: always()
        run: |
          az logout